name: my_quran_reborn
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  provider: ^6.0.5
  google_fonts: ^4.0.3
  http: ^0.13.5
  flutter_custom_tab_bar: ^1.2.1
  contained_tab_bar_view: ^0.8.0
  bottom_bar_matu: ^1.3.0
  dropdown_button2: ^2.0.0
  image_picker: ^0.8.7+1
  rotated_corner_decoration: ^2.1.0+1
  curved_navigation_bar: ^1.0.3
  flutter_staggered_animations: ^1.1.1
  wave_transition: ^0.0.6
  intl: ^0.17.0
  audioplayers: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ic_halaman_utama.png
    - assets/ic_myquran.png
    - assets/ic_juz.png
    - assets/ic_halaman_doa.png
    - assets/ic_halaman_jadwal_sholat.png
    - assets/ic_cloud_night.png
    - assets/ic_cloud_dhuha.png
    - assets/ic_cloud_shubuh.png
    - assets/ic_cloud_terbit.png
    - assets/ic_cloud_zuhur.png
